#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:
    driver: bridge

services:
  ca-org0:
    image: hyperledger/fabric-ca:1.2.0
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_CA_NAME=ca-org0
      - FABRIC_CA_SERVER_CSR_CN=ca-org0
      - FABRIC_CA_SERVER_CSR_HOSTS=ca-org0
      - FABRIC_CA_SERVER_DEBUG=true
      - BOOTSTRAP_USER_PASS=ca-org0-admin:ca-org0-adminpw
      - TARGET_CERTFILE=/data/org0-ca-cert.pem
    ports:
      - 7054:7054
    command: /bin/bash -c '/scripts/bootstrap/start-ca.sh 2>&1 | tee /data/logs/ca-org0.log'
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    container_name: ca-org0
    networks:
      - basic

  setup:
    container_name: setup
    image: hyperledger/fabric-ca-tools:1.2.0
    tty: true
    command: /bin/bash -c '/scripts/bootstrap/start-cli.sh 2>&1 | tee /data/logs/cli.log'
    volumes:
      - /var/run/:/host/var/run/
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - basic
    depends_on:
      - ca-org0

  orderer1-org0:
    container_name: orderer1-org0
    image: hyperledger/fabric-ca-orderer:1.2.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/data/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=org0MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/data/orderers/orderer1-org0/msp
      - ORG=org0
      - ORG_ADMIN_CERT=/data/orgs/org0/admin/msp/admincerts/cert.pem
      - ENROLLMENT_URL=http://orderer1-org0:orderer1-org0pw@ca-org0:7054
      - FABRIC_CA_CLIENT_HOME=/data/orderers/orderer1-org0
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: /bin/bash -c '/scripts/bootstrap/start-orderer.sh 2>&1 | tee /data/logs/orderer1-org0.log'
    ports:
      - 7050:7050
    volumes:
        - ./data:/data
        - ./scripts:/scripts
    networks:
      - basic
    depends_on:
      - setup
